name: Database Sync
on:
  repository_dispatch:
    types: [update_db]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Data
        run: |
          echo '${{ github.event.client_payload.data }}' > data.json
          git config user.name "RoboSpark Bot"
          git config user.email "bot@robospark.com"
          git add data.json
          git commit -m "Mainframe Update"
          git push
